version: 0.2
phases:
  install:
    command:
      - curl -fsSL https://deb.nodesource.com/setup_18.x | -E bash -
      - apt install -y nodejs yarn
  pre-build:
    commands:
      - export NODE_ENV=production
      - yarn install
  build:
    commands: 
      - yarn build
      
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
