version: 0.2
run-as: root
phases:
  install:
    run-as: root
    runtime-versions:
      nodejs: 16
    commands:
      - python --version
      - echo Installing Yarn...
      - npm install -g yarn
  pre_build:
    commands:
      - echo Installing source Yarn dependencies...
      - export NODE_ENV=production
      - yarn install
      - aws secretsmanager get-secret-value --secret-id $SECRET_NAME --query SecretString --output text | python -c 'import json, sys; t = [ print(f"{k}={v}") for k,v in json.load(sys.stdin).items()]' > .env
  build:
    commands: 
      - yarn build
      
artifacts:
  files:
    - build/
    - devops/appspec.yml

