version: 0.2
run-as: root
phases:
  install:
    run-as: root
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing Yarn...
      - npm install -g yarn
  pre-build:
    commands:
      - echo Installing source Yarn dependencies...
      - export NODE_ENV=production
      - yarn install
  build:
    commands: 
      - yarn build
      
artifacts:
  files:
    - build/
    - devops/appspec.yml
