export const coinTosymbol = {
    aave: "aave",
    "binance coin": "BNB",
    bitcoin: "xbt",
    "bitcoin cash": "bch",
    cardano: "ada",
    chainlink: "link",
    compound: "comp",
    dash: "dash",
    defichain: "dfi",
    "doge coin": "doge",
    eos: "eos",
    ethereum: "Eth",
    houbi: "ht",
    iota: "IOTA",
    litecoin: "ltc",
    maker: "MKR",
    monero: "xmr",
    neo: "neo",
    polkadot: "dot",
    stellar: "XLM",
    "sushi swap": "sushi",
    tether: "usdt",
    tezos: "xtz",
    tron: "trx",
    uniswap: "uni",
    vechain: "vet",
    xrp: "xrp",
    "yearn.finance": "yfi",
    zcash: "zec",
    ziliqa: "zil",
    '1inch': "1inch"
}