export const coinTosymbol = {
    "bitcoin" : "BTC",
    "ethereum":"ETH",
    "maker" : "MKR",
    "litecoin" : "LTC",
    "zcash": "ZEC",
    "iota" : "MIOTA",
    "dogecoin" : "DOGE",
    "1inch" : "1INCH",
    "compound" : "COMP",
    "monero" : "XMR",
    "enjin" : "ENJ",
    "ada" : "ADA",
    "stellar" : "XLM",
    "uniswap" : "UNI",
    "solana" : "SOL",
    "xrp" : "XRP",
    "cardano" : "ADA",
    "polkadot" : "DOT",
    "chainlink" : "LINK",
    "aave" : "AAVE",
    "neo" : "NEO",
    "tether" : "USDT",
    "matic" : "MATIC"
}